### ISSUE TITLE
Guide Gong blocks areas before you enter them

### ISSUE THREAD

**Issue by brirush84** [andrewschultz/there-those-dare-doze#1]
I turned on Guide Gong, and it kept me from going east at all, even before I went in it once. Similarly, I first turned it on when I went south, and before I defeated the mar mage, I went back up and it wouldn't let me down.

**Comment by andrewschultz** [comment]
Thanks for this bug report (again!) I think I flipped some logic. This was something I put in near the end of the 4 hour time frame, when it probably would've made more sense to put in rejects for good guesses.

I checked all areas with a new regtest.py scripts, and https://github.com/andrewschultz/there-those-dare-doze/commit/af590e1fec04d3a4fb06a65ca10be78dec9543cc managed to get all tests passed.
